steps:
  - name: 'node'
    entrypoint: 'npm'
    args: [ 'install' ]
  - name: 'node'
    entrypoint: 'npm'
    args: [ 'run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', "-t", "us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/amcart-webapp:v1", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/amcart-webapp:v1']
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
    - run
    - --filename=./manifest/
    - --image=us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/amcart-webapp:v1
    - --location=us-central1
    - --cluster=amcart-cluster
images:
- 'us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/amcart-webapp:v1'
options:
  logging: CLOUD_LOGGING_ONLY
