
kind: Service
apiVersion: v1
metadata:
  name: amcart-webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: amcart-webapp
  ports:
    - port: 4200
      targetPort: 4200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: amcart-webapp-deployment
spec:
  selector:
    matchLabels:
      app: amcart-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: amcart-webapp
    spec:
      containers:
        - name: amcart-webapp
          image: us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/amcart-webapp:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 4200
          resources:
            requests:
              memory: "1Gi"  # Request 64 MiB of memory
              cpu: "250m"      # Request 250 milliCPU (0.25 CPU core)
            limits:
              memory: "1Gi"  # Limit memory usage to 128 MiB
              cpu: "500m"
